thrift_library(
  name = 'common',
  srcs = [ 'common.thrift' ],
)

thrift_library(
  name = 'sp_proxy',
  srcs = [ 'sp_proxy.thrift' ],
)

thrift_library(
  name = 'sp_trade_info',
  srcs = [ 'sp_trade_info.thrift' ],
)
thrift_library(
  name = 'data_center',
  srcs = [ 'data_center.thrift' ],
)

thrift_library(
  name = 'msgcenter',
  srcs = [ 'msgcenter.thrift' ],
)

thrift_library(
  name = 'sms_service',
  srcs = [ 'sms_service.thrift' ],
)

thrift_library(
  name = 'authentication_def',
  srcs = [ 'authentication_def.thrift' ],
)
