// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package authentication_def

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var AuthenErrorStr map[Errno]string

func init() {
	AuthenErrorStr = map[Errno]string{
		0:       "success",
		17:      "login failed",
		13:      "invalid session",
		16:      "wrong password",
		1:       "email address is already existed",
		15:      "email address is not registered",
		18:      "failed to registration",
		8:       "authentication server is not ready",
		9:       "can't generate uid",
		10:      "update database failed",
		11:      "thrift rpc call exception",
		12:      "invalid login info",
		2:       "phone number is already registerred",
		4:       "nick name is already registerred",
		6:       "both phone and nick name are already registered",
		3:       "both phone and email are already registered",
		5:       "both nick name and email are already registered",
		7:       "nick name, phone and email are already registered",
		19:      "invalid bonus url key",
		20:      "bonus url key is expired",
		21:      "phobe number is empty",
		10000:   "can not connect to mt4 server",
		10001:   "no mt4 id info in database",
		10002:   "there is no mt4 live id binding to dedicated user",
		10003:   "bind mt4 id to uid failed",
		20001:   "there is no binding broker info",
		20000:   "the broker user id is already existed",
		9999999: "unknown error",
		14:      "invalide authentication server port",
	}

}
